---
frame:
  time_zone: Asia/Shanghai
  host:
    - 0.0.0.0
  rewrite: false
  mode: mvc
  app_name: cleanPHP
  ver_code: 1
  ver_name: 1.0.0
  log: 30
  cache: ""
redis:
  host: 127.0.0.1
  port: 6379
route:
  "": index/main/index
  index-<dd>-<a>: 'index/ankio/<a>'
  <m>/<c>/<a>: '<m>/<c>/<a>'
database:
  main:
    type: mysql
    host: 127.0.0.1
    username: root
    password: ""
    port: 3306
    db: dx
    charset: utf8
websocket:
  ip: 127.0.0.1
  port: 4405
rbac:
  id_1:
    role_name: 超级管理员
    auth:
      - all
  id_2:
    role_name: 管理员
    auth:
      - user/main/index
      - user/main/logout
      - user/main/admin
      - user/admin
  id_3:
    role_name: 普通用户
    auth:
      - user/main/index
      - user/main/logout
      - user/main/user
      - user/user
