#!/usr/bin/env php
<?php

use server\optimization\common\EmptyFrame;
use server\optimization\common\Release;

include_once __DIR__ . DIRECTORY_SEPARATOR . 'server' . DIRECTORY_SEPARATOR . 'autoload.php';

const BASE_DIR = __DIR__;
function help()
{
    echo <<<EOF
Usage: ./clean [options] 
Options:
  empty                     导出不含拓展的纯净开发包
    --with-cli              导出包含命令行运行功能的
  release                      发布安装包.
    --single                    编译为单一文件.
    --compress                   代码压缩。
    --ignore                    不需要用户介入
    --with-cli
  start                     启动web服务
    [0.0.0.0:80]                
EOF;
    return null;
}


if (!isset($argv[1]))
    return help();

switch ($argv[1]) {
    case "empty":
        EmptyFrame::empty(isset($argv[2]) && $argv[2] === '--with-cli');
        break;
    case "release":
        Release::package($argv);
        break;
    case "start":
        break;
    default:
        help();
}