build: release-compress
release: clean
	./clean release
release-single-compress: clean
	./clean release --ignore --compress --single
release-compress: clean
	./clean release --ignore --compress
clean:
	-rm ../dist
